import PropTypes from 'prop-types';
/*eslint-disable */
/*
 * Generated by the 'fontello-react' Grunt task.
 */
import React from 'react';

class Icon extends React.Component {
    static propTypes = {
        name: PropTypes.oneOf([
            'github-circled-alt2'
        ])
    };

    /**
     * Default the icon to the first one just to show something
     * @return {Object} The default props
     */
    static defaultProps = {
        name: 'github-circled-alt2'
    };

    render() {
        return (
            <span className={'icon icon--' + this.props.name}></span>
        );
    }
}

export default Icon;
