/*eslint-disable */
/*
 * Generated by the 'fontello-react' Grunt task.
 */
import React from 'react';

var Icon = React.createClass({

    propTypes: {
        name: React.PropTypes.oneOf([
            <% _.each(glyphs, function(i, index) { %><%= "'" + i['glyph-name'] + '\'' + (index === glyphs.length-1 ? '' : ',\n\t\t\t') %><% }); %>
        ])
    },

    /**
     * Default the icon to the first one just to show something
     * @return {Object} The default props
     */
    getDefaultProps() {
        return {
            name: '<%= glyphs[0]['glyph-name'] %>'
        };
    },

    render() {
        return (
            <span className={'video-icon video-icon--' + this.props.name}></span>
        );
    }

});

export default Icon;
